---
title: Project Sources
description: |
    A key feature of Packthing is the ability to combine multiple
    source repositories into a single package. This allows the
    bundling of external applications with a primary one.

type: object
properties:
    url:
        title: Source URL
        description: |
            The URL from which to retrieve source code. Currently only Git
            is supported, but future options here will include alternative
            version control systems, as well as local files.

        type: string

    scm:
        enum:
            -   git
            -   svn
            -   hg
            -   cvs
            -   tar
            -   zip

    ref:
        type: string

    tag:
        type: string

    branch:
        type: string

    builders:
        oneOf:
            -   type: object
            -   type: array
                items:
                    type: object

    files:
        oneOf:
            -   type: object
            -   type: array
                items:
                    type: object
required:
    -   url
    -   builders
additionalProperties: False

#not:
#    anyOf:
#        -   required:
#                - tag
#                - ref
#        -   required:
#                - ref
#                - branch
#        -   required:
#                - branch
#                - tag
#
#anyOf:
#    -   required: 
#            -   tag
#    -   required:
#            -   ref
#    -   required:
#            -   branch
#
